// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	BusinessObjects "th3y3m/e-commerce-platform/BusinessObjects"

	Util "th3y3m/e-commerce-platform/Util"

	mock "github.com/stretchr/testify/mock"
)

// ICartItemService is an autogenerated mock type for the ICartItemService type
type ICartItemService struct {
	mock.Mock
}

// DeleteCartItem provides a mock function with given fields: cartID, productID
func (_m *ICartItemService) DeleteCartItem(cartID string, productID string) error {
	ret := _m.Called(cartID, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(cartID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCartItems provides a mock function with given fields:
func (_m *ICartItemService) GetAllCartItems() ([]BusinessObjects.CartItem, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCartItems")
	}

	var r0 []BusinessObjects.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]BusinessObjects.CartItem, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []BusinessObjects.CartItem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BusinessObjects.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCartItemByCartID provides a mock function with given fields: cartItemID
func (_m *ICartItemService) GetCartItemByCartID(cartItemID string) ([]BusinessObjects.CartItem, error) {
	ret := _m.Called(cartItemID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartItemByCartID")
	}

	var r0 []BusinessObjects.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]BusinessObjects.CartItem, error)); ok {
		return rf(cartItemID)
	}
	if rf, ok := ret.Get(0).(func(string) []BusinessObjects.CartItem); ok {
		r0 = rf(cartItemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BusinessObjects.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cartItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedCartItemList provides a mock function with given fields: searchValue, sortBy, cartId, productId, pageIndex, pageSize
func (_m *ICartItemService) GetPaginatedCartItemList(searchValue string, sortBy string, cartId string, productId string, pageIndex int, pageSize int) (Util.PaginatedList[BusinessObjects.CartItem], error) {
	ret := _m.Called(searchValue, sortBy, cartId, productId, pageIndex, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedCartItemList")
	}

	var r0 Util.PaginatedList[BusinessObjects.CartItem]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int) (Util.PaginatedList[BusinessObjects.CartItem], error)); ok {
		return rf(searchValue, sortBy, cartId, productId, pageIndex, pageSize)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int) Util.PaginatedList[BusinessObjects.CartItem]); ok {
		r0 = rf(searchValue, sortBy, cartId, productId, pageIndex, pageSize)
	} else {
		r0 = ret.Get(0).(Util.PaginatedList[BusinessObjects.CartItem])
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, int, int) error); ok {
		r1 = rf(searchValue, sortBy, cartId, productId, pageIndex, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveItemFromCart provides a mock function with given fields: cartId, productId
func (_m *ICartItemService) RemoveItemFromCart(cartId string, productId string) error {
	ret := _m.Called(cartId, productId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItemFromCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(cartId, productId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCartItem provides a mock function with given fields: cartItem
func (_m *ICartItemService) UpdateCartItem(cartItem BusinessObjects.CartItem) error {
	ret := _m.Called(cartItem)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(BusinessObjects.CartItem) error); ok {
		r0 = rf(cartItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICartItemService creates a new instance of ICartItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICartItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICartItemService {
	mock := &ICartItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
