// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	BusinessObjects "th3y3m/e-commerce-platform/BusinessObjects"

	Util "th3y3m/e-commerce-platform/Util"

	mock "github.com/stretchr/testify/mock"
)

// IFreightRateService is an autogenerated mock type for the IFreightRateService type
type IFreightRateService struct {
	mock.Mock
}

// CalculateFreightRate provides a mock function with given fields: courierId, distance
func (_m *IFreightRateService) CalculateFreightRate(courierId string, distance float64) (float64, error) {
	ret := _m.Called(courierId, distance)

	if len(ret) == 0 {
		panic("no return value specified for CalculateFreightRate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (float64, error)); ok {
		return rf(courierId, distance)
	}
	if rf, ok := ret.Get(0).(func(string, float64) float64); ok {
		r0 = rf(courierId, distance)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(courierId, distance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFreightRate provides a mock function with given fields: courierId, distanceMinKm, distanceMaxKm, costPerKm
func (_m *IFreightRateService) CreateFreightRate(courierId string, distanceMinKm int, distanceMaxKm int, costPerKm float64) error {
	ret := _m.Called(courierId, distanceMinKm, distanceMaxKm, costPerKm)

	if len(ret) == 0 {
		panic("no return value specified for CreateFreightRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, int, float64) error); ok {
		r0 = rf(courierId, distanceMinKm, distanceMaxKm, costPerKm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFreightRate provides a mock function with given fields: rateID
func (_m *IFreightRateService) DeleteFreightRate(rateID string) error {
	ret := _m.Called(rateID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFreightRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(rateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllFreightRates provides a mock function with given fields:
func (_m *IFreightRateService) GetAllFreightRates() ([]BusinessObjects.FreightRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllFreightRates")
	}

	var r0 []BusinessObjects.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]BusinessObjects.FreightRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []BusinessObjects.FreightRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BusinessObjects.FreightRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFreightRateByCourierID provides a mock function with given fields: id
func (_m *IFreightRateService) GetFreightRateByCourierID(id string) ([]BusinessObjects.FreightRate, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFreightRateByCourierID")
	}

	var r0 []BusinessObjects.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]BusinessObjects.FreightRate, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []BusinessObjects.FreightRate); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BusinessObjects.FreightRate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFreightRateByID provides a mock function with given fields: rateID
func (_m *IFreightRateService) GetFreightRateByID(rateID string) (BusinessObjects.FreightRate, error) {
	ret := _m.Called(rateID)

	if len(ret) == 0 {
		panic("no return value specified for GetFreightRateByID")
	}

	var r0 BusinessObjects.FreightRate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (BusinessObjects.FreightRate, error)); ok {
		return rf(rateID)
	}
	if rf, ok := ret.Get(0).(func(string) BusinessObjects.FreightRate); ok {
		r0 = rf(rateID)
	} else {
		r0 = ret.Get(0).(BusinessObjects.FreightRate)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedFreightRateList provides a mock function with given fields: searchValue, sortBy, courierID, pageIndex, pageSize, status
func (_m *IFreightRateService) GetPaginatedFreightRateList(searchValue string, sortBy string, courierID string, pageIndex int, pageSize int, status *bool) (Util.PaginatedList[BusinessObjects.FreightRate], error) {
	ret := _m.Called(searchValue, sortBy, courierID, pageIndex, pageSize, status)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedFreightRateList")
	}

	var r0 Util.PaginatedList[BusinessObjects.FreightRate]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, int, int, *bool) (Util.PaginatedList[BusinessObjects.FreightRate], error)); ok {
		return rf(searchValue, sortBy, courierID, pageIndex, pageSize, status)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, int, int, *bool) Util.PaginatedList[BusinessObjects.FreightRate]); ok {
		r0 = rf(searchValue, sortBy, courierID, pageIndex, pageSize, status)
	} else {
		r0 = ret.Get(0).(Util.PaginatedList[BusinessObjects.FreightRate])
	}

	if rf, ok := ret.Get(1).(func(string, string, string, int, int, *bool) error); ok {
		r1 = rf(searchValue, sortBy, courierID, pageIndex, pageSize, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFreightRate provides a mock function with given fields: rateID, courierId, distanceMinKm, distanceMaxKm, costPerKm, status
func (_m *IFreightRateService) UpdateFreightRate(rateID string, courierId string, distanceMinKm int, distanceMaxKm int, costPerKm float64, status bool) error {
	ret := _m.Called(rateID, courierId, distanceMinKm, distanceMaxKm, costPerKm, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFreightRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int, int, float64, bool) error); ok {
		r0 = rf(rateID, courierId, distanceMinKm, distanceMaxKm, costPerKm, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIFreightRateService creates a new instance of IFreightRateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFreightRateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFreightRateService {
	mock := &IFreightRateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
