// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	BusinessObjects "th3y3m/e-commerce-platform/BusinessObjects"

	Util "th3y3m/e-commerce-platform/Util"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// INewsRepository is an autogenerated mock type for the INewsRepository type
type INewsRepository struct {
	mock.Mock
}

// CreateNew provides a mock function with given fields: ctx, news
func (_m *INewsRepository) CreateNew(ctx context.Context, news BusinessObjects.News) error {
	ret := _m.Called(ctx, news)

	if len(ret) == 0 {
		panic("no return value specified for CreateNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, BusinessObjects.News) error); ok {
		r0 = rf(ctx, news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteNew provides a mock function with given fields: ctx, newsID
func (_m *INewsRepository) DeleteNew(ctx context.Context, newsID string) error {
	ret := _m.Called(ctx, newsID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, newsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllNews provides a mock function with given fields: ctx
func (_m *INewsRepository) GetAllNews(ctx context.Context) ([]BusinessObjects.News, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNews")
	}

	var r0 []BusinessObjects.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]BusinessObjects.News, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []BusinessObjects.News); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BusinessObjects.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewByID provides a mock function with given fields: ctx, newsID
func (_m *INewsRepository) GetNewByID(ctx context.Context, newsID string) (BusinessObjects.News, error) {
	ret := _m.Called(ctx, newsID)

	if len(ret) == 0 {
		panic("no return value specified for GetNewByID")
	}

	var r0 BusinessObjects.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (BusinessObjects.News, error)); ok {
		return rf(ctx, newsID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) BusinessObjects.News); ok {
		r0 = rf(ctx, newsID)
	} else {
		r0 = ret.Get(0).(BusinessObjects.News)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, newsID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedNewsList provides a mock function with given fields: ctx, searchValue, sortBy, newId, authorID, pageIndex, pageSize, status
func (_m *INewsRepository) GetPaginatedNewsList(ctx context.Context, searchValue string, sortBy string, newId string, authorID string, pageIndex int, pageSize int, status *bool) (Util.PaginatedList[BusinessObjects.News], error) {
	ret := _m.Called(ctx, searchValue, sortBy, newId, authorID, pageIndex, pageSize, status)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedNewsList")
	}

	var r0 Util.PaginatedList[BusinessObjects.News]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, int, *bool) (Util.PaginatedList[BusinessObjects.News], error)); ok {
		return rf(ctx, searchValue, sortBy, newId, authorID, pageIndex, pageSize, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, int, *bool) Util.PaginatedList[BusinessObjects.News]); ok {
		r0 = rf(ctx, searchValue, sortBy, newId, authorID, pageIndex, pageSize, status)
	} else {
		r0 = ret.Get(0).(Util.PaginatedList[BusinessObjects.News])
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int, int, *bool) error); ok {
		r1 = rf(ctx, searchValue, sortBy, newId, authorID, pageIndex, pageSize, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNew provides a mock function with given fields: ctx, news
func (_m *INewsRepository) UpdateNew(ctx context.Context, news BusinessObjects.News) error {
	ret := _m.Called(ctx, news)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, BusinessObjects.News) error); ok {
		r0 = rf(ctx, news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINewsRepository creates a new instance of INewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINewsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INewsRepository {
	mock := &INewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
