// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	BusinessObjects "th3y3m/e-commerce-platform/BusinessObjects"

	Util "th3y3m/e-commerce-platform/Util"

	mock "github.com/stretchr/testify/mock"
)

// IReviewRepository is an autogenerated mock type for the IReviewRepository type
type IReviewRepository struct {
	mock.Mock
}

// CreateReview provides a mock function with given fields: review
func (_m *IReviewRepository) CreateReview(review BusinessObjects.Review) error {
	ret := _m.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(BusinessObjects.Review) error); ok {
		r0 = rf(review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReview provides a mock function with given fields: reviewID
func (_m *IReviewRepository) DeleteReview(reviewID string) error {
	ret := _m.Called(reviewID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(reviewID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllReviews provides a mock function with given fields:
func (_m *IReviewRepository) GetAllReviews() ([]BusinessObjects.Review, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllReviews")
	}

	var r0 []BusinessObjects.Review
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]BusinessObjects.Review, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []BusinessObjects.Review); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BusinessObjects.Review)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedReviewList provides a mock function with given fields: sortBy, reviewID, userID, productID, pageIndex, pageSize, minRating, maxRating, status
func (_m *IReviewRepository) GetPaginatedReviewList(sortBy string, reviewID string, userID string, productID string, pageIndex int, pageSize int, minRating *int, maxRating *int, status *bool) (Util.PaginatedList[BusinessObjects.Review], error) {
	ret := _m.Called(sortBy, reviewID, userID, productID, pageIndex, pageSize, minRating, maxRating, status)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedReviewList")
	}

	var r0 Util.PaginatedList[BusinessObjects.Review]
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int, *int, *int, *bool) (Util.PaginatedList[BusinessObjects.Review], error)); ok {
		return rf(sortBy, reviewID, userID, productID, pageIndex, pageSize, minRating, maxRating, status)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int, *int, *int, *bool) Util.PaginatedList[BusinessObjects.Review]); ok {
		r0 = rf(sortBy, reviewID, userID, productID, pageIndex, pageSize, minRating, maxRating, status)
	} else {
		r0 = ret.Get(0).(Util.PaginatedList[BusinessObjects.Review])
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, int, int, *int, *int, *bool) error); ok {
		r1 = rf(sortBy, reviewID, userID, productID, pageIndex, pageSize, minRating, maxRating, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewByID provides a mock function with given fields: reviewID
func (_m *IReviewRepository) GetReviewByID(reviewID string) (BusinessObjects.Review, error) {
	ret := _m.Called(reviewID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewByID")
	}

	var r0 BusinessObjects.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (BusinessObjects.Review, error)); ok {
		return rf(reviewID)
	}
	if rf, ok := ret.Get(0).(func(string) BusinessObjects.Review); ok {
		r0 = rf(reviewID)
	} else {
		r0 = ret.Get(0).(BusinessObjects.Review)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(reviewID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReview provides a mock function with given fields: review
func (_m *IReviewRepository) UpdateReview(review BusinessObjects.Review) error {
	ret := _m.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(BusinessObjects.Review) error); ok {
		r0 = rf(review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIReviewRepository creates a new instance of IReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReviewRepository {
	mock := &IReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
